In [3]:
import numpy as np

In [9]:
x = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
print(x)
print(x[0])
print(x[1])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [6]:
np.swapaxes(x,0,2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [8]:
x = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
np.swapaxes(x,0,1)

array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [6, 7]]])

In [11]:
y = 0*x
print(y)

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


In [12]:
x.shape

(2, 2, 2)